# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_processar_dados.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tela(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(420, 385)
        self.arquivo1_entrada = QtWidgets.QLineEdit(Dialog)
        self.arquivo1_entrada.setGeometry(QtCore.QRect(10, 40, 321, 31))
        self.arquivo1_entrada.setObjectName("arquivo1_entrada")
        self.arquivo2_entrada = QtWidgets.QLineEdit(Dialog)
        self.arquivo2_entrada.setGeometry(QtCore.QRect(10, 100, 321, 31))
        self.arquivo2_entrada.setObjectName("arquivo2_entrada")
        self.Selecionar_arquivo1 = QtWidgets.QPushButton(Dialog)
        self.Selecionar_arquivo1.setGeometry(QtCore.QRect(330, 40, 81, 31))
        self.Selecionar_arquivo1.setStyleSheet("")
        self.Selecionar_arquivo1.setObjectName("Selecionar_arquivo1")
        self.Selecionar_arquivo2 = QtWidgets.QPushButton(Dialog)
        self.Selecionar_arquivo2.setGeometry(QtCore.QRect(330, 100, 81, 31))
        self.Selecionar_arquivo2.setStyleSheet("")
        self.Selecionar_arquivo2.setObjectName("Selecionar_arquivo2")
        self.upload_1 = QtWidgets.QPushButton(Dialog)
        self.upload_1.setGeometry(QtCore.QRect(10, 200, 191, 51))
        self.upload_1.setObjectName("upload_1")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 80, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_2.setObjectName("label_2")
        self.campo_de_status = QtWidgets.QLineEdit(Dialog)
        self.campo_de_status.setGeometry(QtCore.QRect(10, 340, 401, 31))
        self.campo_de_status.setPlaceholderText("")
        self.campo_de_status.setObjectName("campo_de_status")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 320, 55, 16))
        self.label_3.setObjectName("label_3")
        self.output_path = QtWidgets.QLineEdit(Dialog)
        self.output_path.setGeometry(QtCore.QRect(10, 160, 321, 31))
        self.output_path.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.output_path.setObjectName("output_path")
        self.output_label = QtWidgets.QLabel(Dialog)
        self.output_label.setGeometry(QtCore.QRect(10, 140, 61, 16))
        self.output_label.setObjectName("output_label")
        self.selecionar_output_path = QtWidgets.QPushButton(Dialog)
        self.selecionar_output_path.setGeometry(QtCore.QRect(330, 160, 81, 31))
        self.selecionar_output_path.setStyleSheet("")
        self.selecionar_output_path.setObjectName("selecionar_output_path")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(210, 200, 201, 51))
        self.pushButton.setChecked(False)
        self.pushButton.setObjectName("pushButton")
        self.upload_2 = QtWidgets.QPushButton(Dialog)
        self.upload_2.setGeometry(QtCore.QRect(10, 250, 191, 51))
        self.upload_2.setObjectName("upload_2")
        self.go_button = QtWidgets.QPushButton(Dialog)
        self.go_button.setGeometry(QtCore.QRect(210, 250, 201, 51))
        self.go_button.setObjectName("go_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.arquivo1_entrada.setPlaceholderText(_translate("Dialog", "D:\\folder 1"))
        self.arquivo2_entrada.setPlaceholderText(_translate("Dialog", "D:\\folder 2"))
        self.Selecionar_arquivo1.setText(_translate("Dialog", "..."))
        self.Selecionar_arquivo2.setText(_translate("Dialog", "..."))
        self.upload_1.setText(_translate("Dialog", "Upload1"))
        self.label.setText(_translate("Dialog", "File 2:"))
        self.label_2.setText(_translate("Dialog", "File 1:"))
        self.label_3.setText(_translate("Dialog", "Status"))
        self.output_path.setPlaceholderText(_translate("Dialog", "D:\\output"))
        self.output_label.setText(_translate("Dialog", "Output:"))
        self.selecionar_output_path.setText(_translate("Dialog", "..."))
        self.pushButton.setText(_translate("Dialog", "Clear DB"))
        self.upload_2.setText(_translate("Dialog", "Upload2"))
        self.go_button.setText(_translate("Dialog", "Output"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_tela()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
